<a href="https://colab.research.google.com/github/souptiks/Logistic-Regression-/blob/main/Company_Hiring_Logistic_Regeression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


In [ ]:
df = pd.read_csv("Company_Hiring_DataSet.csv")

In [ ]:
df

Company Size    Industry    Revenue       Location  \
0              150  Technology   50000000  San Francisco   
1              300  Healthcare    8000000       New York   
2               75     Finance   20000000         London   
3              200  Technology   35000000      Bangalore   
4              100     Finance   15000000        Chicago   
...            ...         ...        ...            ...   
1321           250  Technology   62000000          Paris   
1322           380     Finance   39000000         Berlin   
1323           200  Healthcare   10100000         Madrid   
1324           350  Technology  103000000      Amsterdam   
1325           110     Finance   32000000           Rome   

      Employee Turnover Rate Employee Skillset  Job Openings  \
0                         10            Python            10   
1                          5              Java             5   
2                          8               SQL             8   
3                         12               C++            15   
4                          6        Management             3   
...                      ...               ...           ...   
1321                      16        JavaScript            28   
1322                      19               SQL            25   
1323                      14              Java            22   
1324                      17            Python            33   
1325                      20        Management            27   

      Recruitment Budget  Company Age  Growth Rate Likely to Hire  
0                  50000            5            8            Yes  
1                  30000           10            5             No  
2                  40000            3           12            Yes  
3                  60000            7           10            Yes  
4                  20000            4            6             No  
...                  ...          ...          ...            ...  
1321               70000            9           12            Yes  
1322               56000            8           13            Yes  
1323               55000           13            8            Yes  
1324               81000           10           13            Yes  
1325               38000            8           11            Yes  

[1326 rows x 11 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df['Company Size'], df['Likely to Hire'], test_size = 0.1)


In [ ]:
x_test

349     660
510     140
821     110
1150    300
445     210
       ... 
507     320
505     280
306     820
1124    150
214     620
Name: Company Size, Length: 133, dtype: int64

In [ ]:
x_train

647     300
61      200
783     190
227     700
558      80
       ... 
53      280
1315    190
637     270
388     630
869     150
Name: Company Size, Length: 1193, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
x_train_reshaped = x_train.values.reshape(-1, 1)
model.fit(x_train_reshaped, y_train)


LogisticRegression()

In [ ]:
x_test_reshaped = x_test.values.reshape(-1, 1)
y_test_reshaped = y_test.values.reshape(-1,1)
model_predict = model.predict(x_test_reshaped)



In [ ]:
x_test_reshaped = x_test.values.reshape(-1, 1)
model.score(x_test_reshaped, y_test_reshaped)


0.8646616541353384

In [ ]:
confusion_matrix(y_true= y_test, y_pred= model_predict)

array([[  0,  18],
       [  0, 115]])

In [ ]:

# Create a label encoder
le = LabelEncoder()

# Fit the encoder and transform y_test and model_predict
y_test = le.fit_transform(y_test)
model_predict = le.transform(model_predict)

# Now you can use this in your confusion matrix
confusion_matrix(y_test, model_predict, labels=[1,0])


array([[115,   0],
       [ 18,   0]])

In [ ]:
confusion_matrix(y_test, model_predict, labels=(1,0)).ravel()

array([115,   0,  18,   0])

In [ ]:

TP,FN,FP,TN = confusion_matrix(y_test, model_predict, labels=(1,0)).ravel()

In [ ]:
SUCCESS_RATE = (TP + TN) / (TP + FP + TN + FN)
SUCCESS_RATE

0.8646616541353384

In [ ]:
PRECISION = TP / (TP + FP)
PRECISION

0.8646616541353384

In [ ]:
RECALL = TP / (TP + FN)
RECALL

1.0

In [ ]:
ERROR_RATE = 1 - SUCCESS_RATE
ERROR_RATE

0.13533834586466165

In [ ]:
SPECIFITY = TN / (TN + FP)
SPECIFITY

0.0

In [ ]:
F1_SCORE = 2 * ((PRECISION*RECALL)/(PRECISION+RECALL))
F1_SCORE

0.9274193548387097

In [ ]:
FALSE_POSITIVE_RATE = FP / (FP + TN)
FALSE_POSITIVE_RATE

1.0

In [ ]:
TRUE_NEGTIVE_RATE = TN / (FP + TN)
TRUE_NEGTIVE_RATE

0.0

In [ ]:
AUC_ROC = (1/2) * (RECALL + SPECIFITY)
AUC_ROC

0.5